# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-10 17:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('docentes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(max_length=255)),
                ('codigo', models.CharField(max_length=10)),
                ('vacantes', models.PositiveIntegerField(default=0)),
                ('fecha_de_inicio', models.DateTimeField()),
                ('fecha_de_termino', models.DateTimeField()),
                ('docente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='docentes.Docente')),
            ],
        ),
    ]
